# Generated by Django 6.0.7 on 2026-07-22 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 7, 22)),
            preserve_default=False,
        ),
    ]
